[project]
name = "pdf-redact-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdf-redactor>=0.0.1",
    "pymupdf>=1.26.0",
]
